meta_title: "Trainee plus"
meta_description: "Trouve ton stage gratuitement à l'étranger avec Trainee + !"
meta_image: "Tactica.png" # Une image dans votre dossier app/assets/images/
linkedin_account: "Trainee +"
