meta_title: "Trainee +"
meta_description: "Trouve ton stage à l'étranger gratuitement avec Trainee + !"
meta_image: "Tactica.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@trainee_plus"
